import CategoriesBar from './components/CategoriesBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navContainer">
          <h1>CocktailsDB - DEMO</h1>
          <div className='categoriesContainer'>
            <CategoriesBar />
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
